service: Loatodo-Boards

plugins:

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x
  stage: prod
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          