service: Loatodo-Boards

plugins:
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x
  stage: prod
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: get
          path: /api-docs
          cors: true
    package:
      exclude:
        - node_modules/**
        - src/**
        - tests/**
        - .git/**
        - .gitignore
        - serverless.yaml
        - README.md
        - package.json
        - package-lock.json

custom:
  optimize:
    external: ['swagger-ui-dist']
