service: Loatodo-Boards

plugins:

package:
  patterns:
    - '!.git/**'
    - '!src/**'
    - '!node_modules/@types/**'
    - '!node_modules/serverless/**'
    - '!node_modules/.cache/**'
    - '!node_modules/aws-sdk/**'

provider:
  name: aws
  memorySize: 512
  timeout: 900
  region: ap-northeast-2
  runtime: nodejs18.x
  stage: prod
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/lambda.handler
    package:
      patterns:
        - '!.git/**'
        - '!src/**'
        - '!node_modules/@types/**'
        - '!node_modules/serverless/**'
        - '!node_modules/serverless-plugin-warmup/**'
        - '!node_modules/serverless-domain-manager/**'
        - '!node_modules/.cache/**'
        - '!node_modules/.yarn/**'
        - '!node_modules/aws-sdk/**'
        - '!node_modules/@nestjs/cli/**'
        - '!node_modules/@nestjs/test/**'
        - '!node_modules/eslint/**'
        - '!node_modules/jest/**'
        - '!node_modules/ts-jest/**'
        - '!node_modules/eslint-plugin-import-newlines/**'
        - '!node_modules/ts-node/**'
        - '!node_modules/source-map-support/**'
        - '!node_modules/typescript/**'
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
